# Generated by Django 3.2.20 on 2023-08-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20230824_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('exchange_rate', models.FloatField()),
                ('time_utc', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
    ]
